spring:
  mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: user
        password: pass
  datasource:
    hikari:
      login-timeout: 1000
      maximum-pool-size: 10

props:
    env: prod
    gate: 123
    welcomeMessage: mesaj
    supportUrls:
        - http://stackoverflow.com
        - http://baeldung.com
        - http://spring.io
    contactPhones:
        FR: 430123414123
        RO: 401312121414
    help:
        app-id: 1251
#        file: c:/help-file.pdf
        email: help@spring.io
    tenants:
      FR:
        greeting: Bonjour!
        lunch: PT3h
      RO:
        greeting: Salut!
        lunch: PT30m
    tenants-list:
      - greeting: Bonjour!
        lunch: PT3h
      - greeting: Salut!
        lunch: PT30m
thread-pool:
  core-pool-size: 5
  max-pool-size: ${thread-pool.core-pool-size}
  queue-capacity: 500
  thread-name-prefix: worker-

#thread-pool.threads: 5
management:
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # nu in prod
#server:
#  shutdown: graceful
#thread-pool.queue: 500