db.password: big secret

spring:
    mail:
        host: smtp.gmail.com
        password: <login password to smtp server>
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: <login user to smtp server>

props:
    gate: 123
    welcomeMessage: Hi
    supportUrls:
        - http://stackoverflow.com
#        - http://baeldung.com
#        - http://spring.io
    contactPhones:
        FR: 430123414123
        RO: 401312121414
    help:
        app-id: 1251
        file: c:/help-file.pdf
        email: help@spring.io
